# Generated by Django 5.0 on 2023-12-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('user', '0003_alter_customuser_phone_alter_customuser_third_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='grades',
            field=models.ManyToManyField(to='user.grade'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='subjects',
            field=models.ManyToManyField(to='competition.subject'),
        ),
        migrations.AddField(
            model_name='competition',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
    ]
