# Generated by Django 5.0 on 2023-12-09 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
