# Generated by Django 5.0 on 2023-12-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_attempt_started_at_alter_attempt_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='options',
            field=models.ManyToManyField(null=True, to='competition.option'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
