# Generated by Django 5.0 on 2023-12-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_attempt_options_alter_attempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
            preserve_default=False,
        ),
    ]
