# Generated by Django 5.0 on 2023-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_attempt_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
