# Generated by Django 5.0 on 2023-12-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_attempt_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.subject'),
        ),
    ]
