# Generated by Django 5.0 on 2024-01-06 04:39

import ckeditor.fields
import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=datetime.datetime.now)),
                ('finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(null=True)),
                ('score', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('subtitle', models.CharField(max_length=200, null=True, verbose_name='subtitle')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='description')),
                ('start_at', models.DateTimeField(null=True)),
                ('terminated', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
            ],
        ),
    ]
