# Generated by Django 5.0 on 2024-01-06 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('schoolbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolbook.subject'),
        ),
    ]
