# Generated by Django 5.0 on 2024-01-08 18:39

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolbook', '0003_module_instructors_alter_lesson_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(to='schoolbook.subject')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
