# Generated by Django 5.0 on 2024-01-01 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbook', '0001_initial'),
        ('user', '0002_rename_third_name_customuser_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbook',
            name='grade',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='user.grade'),
        ),
    ]
