# Generated by Django 5.0 on 2024-01-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbook', '0003_module_remove_lesson_school_book_remove_lesson_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolbook',
            options={'ordering': ['subject']},
        ),
        migrations.AlterField(
            model_name='schoolbook',
            name='modules',
            field=models.ManyToManyField(null=True, to='schoolbook.module'),
        ),
    ]
