# Generated by Django 5.0 on 2024-01-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbook', '0004_alter_schoolbook_options_alter_schoolbook_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolbook',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='school_books',
            field=models.ManyToManyField(to='schoolbook.schoolbook'),
        ),
    ]
