# Generated by Django 5.0 on 2023-12-26 15:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-finished_at']},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['start_at']},
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='subtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=100, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
