# Generated by Django 5.0 on 2024-02-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-start_at']},
        ),
        migrations.AlterField(
            model_name='attempt',
            name='options',
            field=models.ManyToManyField(blank=True, to='competition.option'),
        ),
    ]
