# Generated by Django 5.0 on 2024-01-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_attempt_options_alter_competition_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
    ]
