# Generated by Django 4.2 on 2024-02-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_alter_competition_options_alter_attempt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='options',
            field=models.ManyToManyField(to='competition.option'),
        ),
    ]
